### ISSUE TITLE
Unable to Claim LR1110 Modem-E version

### ISSUE THREAD

**Issue by singamsettyvinay** [Lora-net/lr1110_modem_application_example#1]
On LR1110 EVK transceiver version using the LoRaMac node - Periodic Uplink LPP application, we have extracted the Chip EUI and PIN from the chip and claimed the device on Semtech LoRa Cloud Device Join server. The device claim was successful.

![image](https://user-images.githubusercontent.com/26044311/97950329-86f21000-1dbc-11eb-96db-ff6e2b8347f6.png)
![image](https://user-images.githubusercontent.com/26044311/97950399-b99c0880-1dbc-11eb-9c2f-b9646bb5144b.png)

We then unclaimed the device from the Device Join server and upgraded from LR1110 transceiver to LR1110 Modem-E version using the update tool. Using the LR1110-LoRaWAN modem example application, we have extracted the Chip EUI and PIN on the Modem-E version and tried to claim the device. The device claim was unsuccessful. We have tried by changing the endianness of the PIN, but it was giving the same error, **“[Bad Claim] Claim does not verify”**. 

![image](https://user-images.githubusercontent.com/26044311/97950614-7d1cdc80-1dbd-11eb-80d3-51e5aab9f008.png)
![image](https://user-images.githubusercontent.com/26044311/97950651-9d4c9b80-1dbd-11eb-91a6-7ff81812a7b2.png)
![image](https://user-images.githubusercontent.com/26044311/97950690-c2d9a500-1dbd-11eb-9bbf-e7d424be3c29.png)

We have also tried using the derivedkeys command and used that PIN to claim the device. Even then the claim was unsuccessful. Can anyone tell us how to claim the device for modem-e version?

During this process we have observed that Join EUI is different for transceiver version and modem version. 
* Does claiming the device have any effect on it? 
* Should we claim the device every time we get a new PIN?

**Comment by WinXprt** [comment]
@matthieuantoine I am also unable to claim.

**Comment by smtcbboulet** [comment]
Hello,

_Does claiming the device have any effect on it?_
absolutely not
_Should we claim the device every time we get a new PIN?_
if you get a new pin it means that you have changed the DevEUI and/or the JoinEUI. so if you have a new PIN you have to claim it again in order to have the new AppKey.

the keys displayed on the terminal are already in the right endianness.

something is weird on your traces, your JoinEUI is set to 00-00-00-00-00-00-00-00, did you change this key in a previous application ? If you have changed the keys and did a lr1110_modem_set_dev_eui and/or lr1110_modem_set_join_eui, the keys are stored in the LR1110 Modem-E flash.

please could you :
    lr1110_modem_set_dev_eui( &lr1110, dev_eui ); // with your dev_eui which is equal to your dev_eui I guess
    lr1110_modem_set_join_eui( &lr1110, join_eui ); // with the join EUI 0x00, 0x16, 0xC0, 0x01, 0xFF, 0xFE, 0x00, 0x01
    lr1110_modem_derive_keys( &lr1110 ); // do a derive key to have the pin code
    lr1110_modem_get_pin( &lr1110, &pin );

claim the device, 

It should work.

regards,

Benjamin

**Comment by singamsettyvinay** [comment]
Thank you Benjamin, 

Claiming device is successful now, after keeping the same JoinEUI and deriving a new PIN.

I tried flashing the `lr1110_modem_command_tool_v1.0.0.bin` firmware and extract the Join EUI using the command tool. The issue still persists, it shows all 0's for Join EUI.

**Comment by WinXprt** [comment]
@smtcbboulet it worked for me as well.

As mentioned by @singamsettyvinay, the issue with JOIN EUI still persists, as it shows all 0's when I try to get using command tool.

Let me know what could be the reason for that?

**Comment by KestrelLuca** [comment]
Hello, 
I'm experiencing the same issue with a brand-new LR1110 (not claimed on the cloud) updated to the latest LoRa Basic modem-E firmware (v.1.1.8).
With this version, I can retrieve chip_uID and PIN. Join_EUI and Dev_EUI are 0's.
I think that this behaviour is to be expected being the LR1110 a brand new device but I have some doubts since, in order to claim a new device e Dev_EUI, Join_EUI and PIN are required.

Dev_EUI should be equal to chip_uID but what about the Join_EUI? and, what about the tracker type to be selected?

I've then downgraded the modem-E to v.1.0.7  and all the keys are readable.
After this, I've Restored the v1.1.8 and the keys are now there with the chip_uID = dev_EUI and join_EUI = SEMTECH_DEFAULT_JOIN_EUI (0x0016C001FFFE0001).
The host application running hasn't changed across the different versions I've tested and I haven't issued either the setDevEUI or the setJoinEUI command so this must have happened internally in the modem-e fw (can't find release notes on either Semtech or nothing obvious on [gitHub ](https://github.com/Lora-net/radio_firmware_images/blob/master/lr1110/modem/CHANGELOG.md)).
Can anyone please clarify this?
